spotinst/spotinst-sdk-go

README.md
Explicitly mention which env vars to set for authentication in `README.md`.
=> Clarify authentication via env vars

service/elastigroup/providers/aws/aws.go
- Route53 getters, setters, and attributes
- Preferred Spot Instance support
=> [src] added Route53 integration support and preferred spot instance support

service/elastigroup/elastigroup_test.go, service/elastigroup/providers/aws/aws.go, service/elastigroup/providers/aws/service.go, service/elastigroup/providers/azure/azure.go, spotinst/version.go
- updated azure variable syntax
- added another azure test
- added instance health check
- added adjustment for Task (AWS)
- added is_enabled for Scaling Policies (AWS)
=> Azure elastigroup build out

service/elastigroup/providers/aws/aws.go, service/elastigroup/providers/aws/service.go
=> Elasticgroup stop deployment

service/ocean/providers/aws/right_sizing.go, service/ocean/providers/aws/service.go
Adding `ListResourceSuggestions` for Ocean AWS
=> Adding right-sizing resource suggestions for Ocean AWS

service/elastigroup/providers/aws/aws.go, service/ocean/providers/aws/launch_spec.go, service/ocean/providers/aws/launch_spec_ecs.go, service/ocean/providers/gcp/launch_spec.go
Added support batch queue in ecs integration under aws elastigroup.
Refactor spot percentage risk from float to int.
Added block device mapping to ocean ecs.
=> merge tasks from liron-ecs-integration to master 

service/ocean/providers/aws/launchspec.go, service/ocean/providers/gcp/launchspec.go
launchSpec gke - instance types
launchSPec aws - preferredSpotTypes
=> feat(ocean/aws): new field: `preferredSpotTypes`

service/elastigroup/providers/aws/aws.go, service/managedinstance/providers/aws/aws.go, service/ocean/providers/gcp/cluster.go
=> ocean-gke-rootVolumeType-elastigroup-aws-resourceTagSpecification

service/ocean/providers/aws/cluster.go, service/ocean/providers/aws/cluster_ecs.go
=> ocean-spot-percentage-IMDSv2

service/mrscaler/mrscaler.go
=> fix instanceGroupType Json tag

service/elastigroup/providers/aws/aws.go
Multiple metrics and Step adjustments
=> Elastigroup_aws-scaling_metrics

service/elastigroup/providers/aws/aws.go
=> ITF Elastigroup AWS

examples/service/ocean/providers/aws/rightsizing/main.go, examples/service/ocean/providers/azure/rightsizing/main.go, service/ocean/providers/aws/rightsizing.go, service/ocean/providers/aws/service.go, service/ocean/providers/azure/rightsizing.go, service/ocean/providers/azure/service.go
=> Ocean AWS and Ocean AKS right sizing APIs

examples/service/stateful/providers/azure/attachDataDisk/main.go, examples/service/stateful/providers/azure/create/main.go, examples/service/stateful/providers/azure/delete/main.go, examples/service/stateful/providers/azure/detachDataDisk/main.go, examples/service/stateful/providers/azure/importVm/main.go, examples/service/stateful/providers/azure/list/main.go, examples/service/stateful/providers/azure/read/main.go, examples/service/stateful/providers/azure/update/main.go, examples/service/stateful/providers/azure/updateState/main.go, service/stateful/providers/azure/service.go, service/stateful/providers/azure/statefulNode.go, service/stateful/providers/stateful.go
=> Stateful Azure - Go SDK

service/ocean/providers/aws/cluster_ecs.go, service/ocean/providers/azure/cluster.go, service/ocean/providers/azure/common.go, service/ocean/providers/azure/nodegroup.go
Added "zones" both in AKS and in AKS_VNG, since the VNG required that it is added in AKS as well.
=> Ocean_ECS_S3_Integration_AND_Ocean_AKS_fields

service/ocean/providers/aws/cluster.go
Adding Respect Pdb field to Ocean AWS
=> Adding Respect Pdb field to Ocean AWS

service/ocean/providers/gcp/cluster.go
Adding Blacklist field to Ocean gke
=> Adding Blacklist field to Ocean gke

service/ocean/providers/azure/cluster.go, service/ocean/providers/azure/nodegroup.go
Adding MaxPods field to Ocean AKS and Ocean AKS VNG - Go SDK
=> Adding MaxPods field to Ocean AKS and Ocean AKS VNG - Go SDK

.github/workflows/ci.yaml, service/elastigroup/providers/aws/aws.go
Support Images in elastigroup aws - GO SDK
=> Support Images in elastigroup aws - GO SDK

service/ocean/providers/aws/launchspec.go
https://spotinst.atlassian.net/browse/PROD-5927
=> added deleteNode for aws ocean VNG and Fixed prod-5927

service/ocean/providers/aws/launchspec_ecs.go
Addition of SetStrategy method
https://spotinst.atlassian.net/browse/PROD-5899 -- added setStrategy method to support spotPercentage attribute
=> Addition of SetStrategy method

examples/service/elastigroup/providers/aws/status/main.go, examples/service/managedinstance/providers/aws/status/main.go, service/elastigroup/providers/aws/aws.go, service/managedinstance/providers/aws/aws.go
JIRA: https://spotinst.atlassian.net/browse/PRD-2219 - Added returning IPV6Address support and examples for AWS Elastigroup and AWS ManagedInstance
=> returning IPV6Address

examples/service/ocean/spark/cluster/create/main.go, examples/service/ocean/spark/cluster/update/main.go, service/ocean/spark/cluster.go
Add Ocean for Apache Spark cluster networking configs
=> Ocean Spark networking configs

examples/service/ocean/providers/aws/create/main.go, examples/service/ocean/providers/aws/update/main.go, service/ocean/providers/aws/cluster.go
JIRA: https://spotinst.atlassian.net/browse/PRD-3291 - Advanced instance types selection for customer.
Added filters object which contains multiple attributes, using which customer can filter and choose the instance types.
=> Prd 3291 ocean instance types

service/ocean/providers/gcp/cluster.go
Added-Respectpdb-To-Roll_Config
Ref: https://spotinst.atlassian.net/browse/PRD-3684
=> Added-Respectpdb-To-Roll_Config

examples/service/elastigroup/providers/aws/create/main.go, service/elastigroup/providers/aws/aws.go
Added considerODPricing capability
Ref: https://spotinst.atlassian.net/browse/PRD-3728
=> Added considerODPricing capability

go.mod, go.sum, vendor/gopkg.in/ini.v1/deprecated.go, vendor/gopkg.in/ini.v1/ini.go, vendor/modules.txt
=> bumped package version

examples/service/ocean/providers/aws/createECS/main.go, service/ocean/providers/aws/cluster_ecs.go
added ShouldScaleDownNonServiceTasks parameter in Ocean/ECS
=> added ShouldScaleDownNonServiceTasks param

examples/service/ocean/providers/aws/create/main.go, service/ocean/providers/aws/cluster.go
JIRA Ticket: https://spotinst.atlassian.net/browse/SPOTAUT-13144
SpreadNodesBy added in Strategy
=> SpreadNodesBy added

examples/service/ocean/providers/azure_np/create/main.go, examples/service/ocean/providers/azure_np/delete/main.go, examples/service/ocean/providers/azure_np/list/main.go, examples/service/ocean/providers/azure_np/nodegroup/create/main.go, examples/service/ocean/providers/azure_np/nodegroup/delete/main.go, examples/service/ocean/providers/azure_np/read/main.go, examples/service/ocean/providers/azure_np/update/main.go, service/ocean/ocean.go, service/ocean/providers/azure_np/cluster_np.go, service/ocean/providers/azure_np/common.go, service/ocean/providers/azure_np/nodegroup_np.go, service/ocean/providers/azure_np/service.go
Create Ocean Cluster using aks-node-pool api
jira: https://spotinst.atlassian.net/browse/SPOTAUT-13527
=> Spotaut-13528-aks-np

examples/service/ocean/providers/aws/create/main.go, service/ocean/providers/aws/cluster.go
=> Spotaut 13698 terraform support for i pv6 addresses in ocean aws

examples/service/elastigroup/providers/aws/create/main.go, service/elastigroup/providers/aws/aws.go
=> Instance metadata tags go sdk support

examples/service/ocean/providers/gcp/create/main.go, service/ocean/providers/gcp/cluster.go
Added suport for respectpdb in roll_configs in scheduledRoll config
https://spotinst.atlassian.net/browse/SPOTAUT-12985
=> Added suport for respectpdb in roll_configs in scheduledRoll config.

service/ocean/providers/gcp/launchspec.go
=> Vng alias ip range go

examples/service/elastigroup/providers/azure/v3/create/main.go, service/elastigroup/providers/azure/v3/azure.go
=> added tags parameter in azurev3

service/ocean/providers/azure_np/common.go
Modified minVCpu and maxVCpu in filters object
https://spotinst.atlassian.net/browse/SPOTAUT-15313
=> filters update

service/stateful/providers/azure/statefulNode.go
Modified privateIpAddresses
https://spotinst.atlassian.net/browse/SPOTAUT-15463
=> Modified privateIpAddresses

examples/service/stateful/providers/azure/create/main.go, examples/service/stateful/providers/azure/importVm/main.go, service/stateful/providers/azure/statefulNode.go
https://spotinst.atlassian.net/browse/SPOTAUT-15408
=> userData for azure stateful node

examples/service/ocean/providers/aws/create/main.go, service/ocean/providers/aws/cluster.go
https://spotinst.atlassian.net/browse/SPOTAUT-15624
=> SPOTAUT-15624 added resource specification tag in ocean aws

examples/service/stateful/providers/azure/create/main.go, service/stateful/providers/azure/statefulNode.go
https://spotinst.atlassian.net/browse/SPOTAUT-15732
=> SPOTAUT-15732 - added vmname in stateful node azure launch spec

examples/service/elastigroup/providers/aws/create/main.go, examples/service/ocean/providers/azure_np/create/main.go, examples/service/ocean/providers/azure_np/nodegroup/create/main.go, service/elastigroup/providers/aws/aws.go, service/ocean/providers/azure_np/common.go
Added support for instanceTypes attributes in AWS Elastigroup
Added support for osSKu and excludeSeries in Ocean_Aks_np
https://spotinst.atlassian.net/browse/SPOTAUT-15811
=> Spotaut 15811 implement the support for attributes in instance types object in sdk and provider

examples/service/stateful/providers/azure/create/main.go, service/stateful/providers/azure/statefulNode.go
https://spotinst.atlassian.net/browse/SPOTAUT-16114
=> SPOTAUT-16114 - CRG for Azure Stateful node

examples/service/ocean/providers/azure_np/create/main.go, examples/service/ocean/providers/azure_np/nodegroup/create/main.go, service/ocean/providers/azure_np/common.go
JIRA: https://spotinst.atlassian.net/browse/SPOTAUT-16468
=> feat (ocean/aks_np): added `kubernetesVersion` attribute in `nodePoolProperties` object

service/ocean/providers/aws/cluster.go
https://spotinst.atlassian.net/browse/SPOTAUT-16487
=> feat(ocean/aws): added `dynamicIops` object

service/ocean/providers/aws/launchspec_ecs.go
Added support for images(Multi arch VNG)
Ref: https://spotinst.atlassian.net/browse/SPOTAUT-17017
=> Added support for images(Multi arch VNG).

examples/service/stateful/providers/azure/create/main.go, service/stateful/providers/azure/statefulNode.go
=> ProximityPlacementGroupChanges

examples/service/elastigroup/providers/aws/create/main.go, service/elastigroup/providers/aws/aws.go
Added support for logging in Elastigroup-AWS.
https://spotinst.atlassian.net/browse/SPOTAUT-17203
=> Added support for logging in Elastigroup-AWS.

examples/service/ocean/providers/aws/listmigrations/main.go, examples/service/ocean/providers/aws/migrationstatus/main.go, examples/service/ocean/providers/aws/readnodes/main.go, service/ocean/providers/aws/clusternodes.go, service/ocean/providers/aws/migrationstatus.go, service/ocean/providers/aws/migrationsummary.go, service/ocean/providers/aws/service.go
Added support for getting cluster nodes details and migration status.
https://spotinst.atlassian.net/browse/SPOTAUT-17383
=> Added support for getting cluster nodes details and migration status.

examples/service/organization/user/create/main.go, examples/service/stateful/providers/azure/create/main.go
removed credentials from example
https://spotinst.atlassian.net/browse/SPOTAUT-17459
=> removed credentials from example

examples/service/ocean/providers/aws/create/main.go, examples/service/ocean/providers/aws/update/main.go, service/ocean/providers/aws/cluster.go
Added support for HealthCheckUnhealthyDurationBeforeReplacement under launchSpecification for ocean-aws.
Ref : https://spotinst.atlassian.net/browse/SPOTAUT-18145
=> Added support for HealthCheckUnhealthyDurationBeforeReplacement under launchSpecification for ocean-aws.

examples/service/stateful/providers/azure/create/main.go, service/stateful/providers/azure/statefulNode.go
added `AvailabilityVsCost`, `OdWindows`, `LicenseType`, `Caching`, `VMNamePrefix` fields
https://spotinst.atlassian.net/browse/SPOTAUT-18234
=> added fields to azure stateful node

examples/service/ocean/providers/azure_np/create/main.go, examples/service/ocean/providers/azure_np/nodegroup/create/main.go, service/ocean/providers/azure_np/common.go
https://spotinst.atlassian.net/browse/SPOTAUT-16188
=> SPOTAUT-16188-Added gpuTypes parameter

service/elastigroup/providers/aws/aws.go, service/managedinstance/providers/aws/aws.go
https://spotinst.atlassian.net/browse/SPOTAUT-18469
=> removed mlbRuntime support

examples/service/ocean/providers/azure_np/launchNewNodes/main.go, service/ocean/providers/azure_np/cluster_np.go, service/ocean/providers/azure_np/service.go
added support for LaunchNewNodes api
https://spotinst.atlassian.net/browse/SPOTAUT-18546
=> feat(ocean/aks-np): added support for LaunchNewNodes api

examples/service/ocean/providers/azure_np/nodegroup/create/main.go, service/ocean/providers/azure_np/common.go
=> sdk implementation for vmmaxmapcount

service/oceancd/verificationTemplate.go
=> Spotaut 18688 - SDK fix for Verification template 'job' object

examples/service/oceancd/rolloutSpec/create/main.go, examples/service/oceancd/rolloutSpec/delete/main.go, examples/service/oceancd/rolloutSpec/list/main.go, examples/service/oceancd/rolloutSpec/patch/main.go, examples/service/oceancd/rolloutSpec/read/main.go, examples/service/oceancd/rolloutSpec/update/main.go, service/oceancd/rolloutSpec.go, service/oceancd/service.go
=> Implemented OceanCD SDK for RolloutSpec

examples/service/ocean/providers/azure_np/create/main.go, service/ocean/providers/azure_np/common.go
Added support for `tasks` under `scheduling` .
Ref: https://spotinst.atlassian.net/browse/SPOTAUT-18112
=> Added support for `tasks` under `scheduling` .

service/stateful/providers/azure/statefulNode.go
Added `spot_account_id` object under `gallery` attribute under `image` and `should_deregister_from_lb` under `delete`.
Ref: https://spotinst.atlassian.net/browse/SPOTAUT-18882
=> Added `spot_account_id` object under `gallery` attribute under `image` and `should_deregister_from_lb` under `delete`.

.github/workflows/ci.yaml, .github/workflows/release.yaml
nodejs version fix for github actions
=> nodejs version fix for github actions

.github/workflows/ci.yaml, .github/workflows/release.yaml
=> GitHub actions fxi nodejs version

service/ocean/providers/gcp/launchspec.go
added initiaNodes as query param
https://spotinst.atlassian.net/browse/SPOTAUT-13257
=> added initiaNodes as query param

examples/service/account/create/main.go, examples/service/setcredentails/providers/gcp/create/main.go, examples/service/setcredentails/providers/gcp/read/main.go, service/account/account.go, service/account/providers/common/account.go, service/account/providers/common/service.go, service/account/providers/gcp/gcpcredentials.go, service/account/providers/gcp/service.go
Added support to create spotinst account and GCP set credentials.
Ref: https://spotinst.atlassian.net/browse/SPOTAUT-19356
=> Added support to create spotinst account and GCP set credentials.

service/stateful/providers/azure/statefulNode.go
added support for `ConfidentialOsDiskEncryption` and `EncryptionAtHost`
https://spotinst.atlassian.net/browse/SPOTAUT-19184
=> added support for `ConfidentialOsDiskEncryption` and `EncryptionAtHost`

service/ocean/providers/aws/launchspec.go
Added drainingTimeout field in LaunchSpecStrategy
https://spotinst.atlassian.net/browse/SPOTAUT-19444
=> Added drainingTimeout field in LaunchSpecStrategy

examples/service/elastigroup/providers/gcp/create/main.go, service/elastigroup/providers/gcp/gcp.go
Added support for `RevertToPreemptible` and `OptimizationWindows` under strategy object.
Ref: https://spotinst.atlassian.net/browse/SPOTAUT-19474
=> Added support for `RevertToPreemptible` and `OptimizationWindows` under strategy object.

service/elastigroup/providers/aws/aws.go
added `ResctrictSingleAz`, `AutoHealin`, `DynamicIOPS` and `DynamicVolumeSize` fields in Elastigroup AWS
https://spotinst.atlassian.net/browse/SPOTAUT-19556
=> added fields in Elastigroup AWS

examples/service/ocean/right_sizing/create/main.go, examples/service/ocean/right_sizing/update/main.go, service/ocean/right_sizing/right_sizing.go
Added support for `RestartReplicas`, `ExcludePreliminaryRecommendations` and `RecommendationApplicationHPA`
Ref: https://spotinst.atlassian.net/browse/SPOTAUT-19437
=> Added support for `RestartReplicas`, `ExcludePreliminaryRecommendations` and `RecommendationApplicationHPA`

service/stateful/providers/azure/statefulNode.go
added VmAdmins field in strategy object of azure stateful node
https://spotinst.atlassian.net/browse/SPOTAUT-19286
=> added VmAdmins field in strategy object of azure stateful node

service/elastigroup/providers/azure/v3/azure.go
Added support for GalleryImage in Elastigroup Azure V3
https://spotinst.atlassian.net/browse/SPOTAUT-19670
=> Added support for GalleryImage in Elastigroup Azure V3

service/ocean/providers/gcp/cluster.go
Added support for `ShouldUtilizeCommitments`
Ref: https://spotinst.atlassian.net/browse/SPOTAUT-19850
=> Added support for `ShouldUtilizeCommitments`.

service/elastigroup/providers/azure/v3/azure.go
added `scaling` object support for azure v3
https://spotinst.atlassian.net/browse/SPOTAUT-19849
=> added `scaling` object support for azure v3

service/elastigroup/providers/azure/v3/azure.go
modified data types for action attributes
https://spotinst.atlassian.net/browse/SPOTAUT-19849
=> modified data types for action attributes

service/elastigroup/providers/azure/v3/azure.go
added `extensions` block support in Elastigroup Azure
https://spotinst.atlassian.net/browse/SI-72
=> added `extensions` block support in Elastigroup Azure

service/elastigroup/providers/azure/v3/azure.go
Added support for all fields in Azure Elastigroup
https://spotinst.atlassian.net/browse/SI-77
=> Added support for all fields in Azure Elastigroup

examples/service/ocean/right_sizing/readAttachedWorkloads/main.go, service/ocean/right_sizing/right_sizing.go, service/ocean/right_sizing/service.go
Added support to get workload attached to rightSizing rule.
Ref: https://spotinst.atlassian.net/browse/SI-84
=> Added support to get workload attached to rightSizing rule.

service/ocean/providers/gcp/cluster.go
https://spotinst.atlassian.net/browse/SI-104
=> added aggressiveScaleDown and filters attributes to ocean gke

service/ocean/providers/aws/cluster.go, service/ocean/providers/aws/launchspec.go
added `ReservedENIs` field to ocean-aws and vng
https://spotinst.atlassian.net/browse/SI-123
=> added `ReservedENIs` field to ocean-aws and vng

service/stateful/providers/azure/statefulNode.go
added `ExcludedVmSizes` and `SpotSizeAttributes` in Azure Stateful Node
https://spotinst.atlassian.net/browse/SI-173
=> added `ExcludedVmSizes` and `SpotSizeAttributes` in Azure Stateful Node

service/stateful/providers/azure/statefulNode.go
Added ShouldRevertToOd field in DeallocationConfig
https://spotinst.atlassian.net/browse/SI-101
=> Added ShouldRevertToOd field in DeallocationConfig

service/ocean/providers/aws/cluster_ecs.go
Added `FallbackToOnDemand` field in ocean_ecs
https://spotinst.atlassian.net/browse/SI-193
=> Added `FallbackToOnDemand` field in ocean_ecs

service/elastigroup/providers/gcp/gcp.go
added `minCpuPlatform`, `preferredAvailabilityZones` and `shouldUtilizeCommitments` in GCP EG
https://spotinst.atlassian.net/browse/SI-201
=> added `minCpuPlatform`, `preferredAvailabilityZones` and `shouldUtilizeCommitments` in GCP EG

examples/service/elastigroup/providers/aws/create/main.go, service/elastigroup/providers/aws/aws.go
Added support of SubnetIDs under AvailabilityZone.
Ref: https://spotinst.atlassian.net/browse/SI-121
=> Added support of SubnetIDs under AvailabilityZone.

examples/service/ocean/providers/gcp/create/main.go, service/ocean/providers/gcp/cluster.go
Added support for `autoUpdate` in ocean-gcp-k8s.
Ref: https://spotinst.atlassian.net/browse/SI-208
=> Added support for `autoUpdate` in ocean-gcp-k8s.

service/managedinstance/providers/aws/aws.go
Added preferredTypes and resourceRequirements to aws statefulnode
https://spotinst.atlassian.net/browse/SI-216
=> Added preferredTypes and resourceRequirements

examples/service/managedinstance/providers/aws/create/main.go
added example to create aws managed instance
https://spotinst.atlassian.net/browse/SI-216
=> added example to create aws managed instance

service/elastigroup/providers/gcp/gcp.go
Added `shieldedInstanceConfig` object to GCP EG
https://spotinst.atlassian.net/browse/SI-244
=> Added `shieldedInstanceConfig` object
