spotinst/spotinst-sdk-go

service/elastigroup/providers/aws/aws.go

- fixed beanstalk syntax (environmentId -> environmentID). This aligns it with the rest of the codebase.

[src] added docker swarm integration support

---

service/elastigroup/providers/aws/aws.go
service/elastigroup/providers/azure/azure.go
service/elastigroup/providers/gcp/gcp.go
service/ocean/providers/aws/ocean.go

[src] adding managedActions and deploymentPreferences to beanstalk
[src] adding loadBalancers and associatePublicIpAddress to Ocean
[src] added spotinstAccountID to domains
[src] added dockerswarm
[src] azure userdata, gcp backend svcs refactor
[src] added integrations for azure, addl fields for gcp, aws

aws, gcp, azure updates

---

service/ocean/providers/aws/right_sizing.go

Add Namespace query param to `ResourceSuggestionInput` object since API require `Namespace` as a mandatory field

Update ResourceSuggestion API call

---

service/elastigroup/providers/aws/aws.go
service/elastigroup/providers/aws/service.go

```go
package main
import (
"context"
"encoding/json"
"fmt"
"github.com/spotinst/spotinst-sdk-go/service/elastigroup"
"github.com/spotinst/spotinst-sdk-go/service/elastigroup/providers/aws"
"github.com/spotinst/spotinst-sdk-go/spotinst"
"github.com/spotinst/spotinst-sdk-go/spotinst/log"
"github.com/spotinst/spotinst-sdk-go/spotinst/session"
)
func main() {
// Initialize context.
ctx := context.Background()
// Initialize service.
cfg := spotinst.DefaultConfig().WithLogger(log.DefaultStdLogger)
svc := elastigroup.New(session.New(cfg)).CloudProviderAWS()
gid := os.Getenv("SPOTINST_GROUP_ID")
// Create suspensions.
Create(ctx, svc, gid)
// List suspensions.
List(ctx, svc, gid)
// Delete suspensions.
Delete(ctx, svc, gid)
// Re-list suspensions after deletion.
List(ctx, svc, gid)
}
// Create …
```

feat(service/elastigroup): Add suspension endpoints

---

service/elastigroup/providers/aws/aws.go

add support for metadataOptions in elastigroup aws

feat(service/elastigroup): Add support for metadataOptions in Elastigroup AWS

---

service/mcs/mcs.go

Hi, I've added the `ebsCost` field and the `totalEbsCost` field because they don't exist in SDK even though [the API of Spotinst](https://docs.spot.io/api/#operation/oceanAwsClusterCosts) is providing these fields. I hope It would be helpful :), or If I missed something please let me know.

feat(mcs): Add ebs cost field.

---

service/managedinstance/providers/aws/aws.go
service/managedinstance/providers/aws/service.go

We are starting to use the spotinst-sdk-go for one of our projects and we needed some additional functionality for Managed Instances (currently, only the basic List, Read, Update, Delete functions are implemented).
This PR adds support for the Managed Instance Status API call which returns additional information from the cloud provider.
I tested it locally and it works as expected. There were no existing tests for this provider, so I haven't written a test for the new function.

Add support for getting managed instance status

---

service/ocean/providers/aws/right_sizing.go

The API also exposes the fields `resourceType` and `resourceName` but these are currently not part of the `ResourceSuggestion` type.
This makes resource suggestions for DaemonSets and StatefulSets not very useful as the information about the resource type and name are missing.
This change adds the missing fields `ResourceName` and `ResourceType` and, while we're at, also adds the missing `Containers` field.

feat(ocean/aws): add missing fields to ResourceSuggestion type

---

service/ocean/providers/gcp/launchspec.go

Add missing fields defined in the ocean gke launch specification. 
These values seem to be supported by the spot API as documented 
https://docs.spot.io/api/#operation/OceanGKELaunchSpecCreate
Potential fix for #126

add missing gke fields

---

service/ocean/providers/azure/cluster.go

This PR adds a new field (`managedServiceIdentities`) to `virtualNodeGroupTemplate.launchSpecification`.

feat(ocean/aks): new field: `managedServiceIdentities`

---

service/ocean/providers/aws/cluster.go
service/ocean/providers/aws/cluster_ecs.go
service/ocean/providers/gcp/cluster.go

Adding the field to ocean aws, ocean ecs and ocean gke import.
Ocean aws documentation - https://docs.spot.io/api/#operation/oceanAwsRollInit
Ocean ecs documentation - https://docs.spot.io/api/#operation/oceanEcsRollInit
Ocean gke import documentation - https://docs.spot.io/api/#operation/oceanGkeRollInit

Adding Batch Min Healthy Percentage field

---

examples/service/dataintegration/providers/aws/create/main.go
examples/service/dataintegration/providers/aws/delete/main.go
examples/service/dataintegration/providers/aws/list/main.go
examples/service/dataintegration/providers/aws/read/main.go
examples/service/dataintegration/providers/aws/update/main.go
service/dataintegration/dataintegration.go
service/dataintegration/providers/aws/aws.go
service/dataintegration/providers/aws/service.go
spotinst/version.go

Adding Data Integration Resource By Tal Geva
https://docs.spot.io/api/#operation/DataIntegrationCreate

Data Integration Resource

---

service/ocean/providers/aws/launchspec_ecs.go

Signed-off-by: Marino Borges <omarinoborges@gmail.com>
This PR provides support for `strategy.spotPercentage` in `spotinst_ocean_ecs_launch_spec` resource ([API docs](https://docs.spot.io/api/#operation/OceanECSLaunchSpecCreate:~:text=virtual%20node%20group.-,spotPercentage,-integer%20%5B%200%20..%20100))

Feat: add support for spot_percentage in Ocean ECS Launch Spec

---

service/ocean/providers/aws/launchspec.go

Added support for "max_scale_down_percentage" in aws ocean vng.
Ref: https://spotinst.atlassian.net/browse/PROD-6135

Added support for "max_scale_down_percentage" in aws ocean vng.

---

examples/service/ocean/providers/aws/createECS/main.go
service/ocean/providers/aws/cluster_ecs.go

Added support for cluster_orientation field in ocean ECS strategy
Ref: https://spotinst.atlassian.net/browse/CON-18943

Added support for cluster_orientation field in ocean ECS strategy

---

examples/service/elastigroup/providers/aws/create/main.go
service/ocean/providers/aws/launchspec.go
service/ocean/providers/aws/launchspec_ecs.go

Added support for instanceMetadataOptions in Ocean AWS and ECS VNG.
Ref: https://spotinst.atlassian.net/browse/SPOTAUT-13265

Spotaut 13265 aws eg ocean tf set access to instance meta data tags

---

examples/service/ocean/spark/cluster/create/main.go
examples/service/ocean/spark/cluster/update/main.go
service/ocean/spark/cluster.go

- Adds Spark config to Ocean Spark cluster config

Ocean Spark cluster spark config

---

examples/service/ocean/spark/cluster/delete/main.go
service/ocean/spark/cluster.go
service/ocean/spark/spark.go

https://spotinst.atlassian.net/browse/BGD-2995
Motivation: 
supply wait-for-deletion query parameter in deletion call
block until the cluster goes away in deletion call
we need to
add support for the new forceDelete query parameter in the spotinst-sdk-go
supply this query parameter in the terraform provider delete cluster call
wait for the cluster to be deleted in the terraform provider

BGD-2995 ForceDelete query param to DeleteCluster

---

examples/service/administration/policy/create/main.go
examples/service/administration/policy/delete/main.go
examples/service/administration/policy/list/main.go
examples/service/administration/policy/read/main.go
examples/service/administration/policy/update/main.go
examples/service/administration/user/create/main.go
examples/service/administration/user/createProg/main.go
examples/service/administration/user/delete/main.go
examples/service/administration/user/list/main.go
examples/service/administration/user/read/main.go
examples/service/administration/userGroup/create/main.go
examples/service/administration/userGroup/delete/main.go
examples/service/administration/userGroup/list/main.go
examples/service/administration/userGroup/read/main.go
examples/service/administration/userGroup/update/main.go
service/administration/policy.go
service/administration/service.go
service/administration/user.go
service/administration/userGroup.go
spotinst/credentials/provider_env.go

https://spotinst.atlassian.net/browse/SPOTAUT-15748

Spotaut 15748- support user management in the terraform provider

---

examples/service/ocean/providers/azure/clusterroll/main.go
examples/service/ocean/providers/azure/listrolls/main.go
examples/service/ocean/providers/azure/readroll/main.go
examples/service/ocean/providers/azure/stoproll/main.go
service/ocean/providers/azure/cluster.go
service/ocean/providers/azure/service.go

Added support for cluster roll.
https://spotinst.atlassian.net/browse/SPOTAUT-17448

Added support for cluster roll 

---

service/ocean/providers/aws/cluster.go

added support for `aggressiveScaleDown` object
https://spotinst.atlassian.net/browse/SPOTAUT-15500

feat(ocean/aws): added support for `aggressiveScaleDown` object

---

examples/service/ocean/providers/aws/launchSpec/create/main.go
service/ocean/providers/aws/launchspec.go

Added support for `ephemeralStorage` in `ocean-aws-k8s-launchspec`.
ref: https://spotinst.atlassian.net/browse/SPOTAUT-17702

Added support for `ephemeralStorage` in `ocean-aws-k8s-launchspec`.

---

examples/service/ocean/providers/aws/attachLoadBalancer/main.go
examples/service/ocean/providers/aws/detachLoadBalancer/main.go
service/ocean/providers/aws/loadbalancer.go
service/ocean/providers/aws/service.go

Added support for attach and detach loadBalancers to ocean aws k8s cluster in go-sdk
https://spotinst.atlassian.net/browse/SPOTAUT-18601

Added support for attach and detach loadBalancers to ocean aws k8s cluster in go-sdk

---

examples/service/ocean/providers/aws/launchSpec/create/main.go
service/ocean/providers/aws/launchspec.go

Added support for `UtilizeCommitments` and `UtilizeReservedInstances` in ocean_aws_launchspec.
Ref: https://spotinst.atlassian.net/browse/SPOTAUT-16900

Added support for `UtilizeCommitments` and `UtilizeReservedInstances` under strategy in ocean_aws_launchspec.

---

examples/service/ocean/spark/cluster/create/main.go
examples/service/ocean/spark/cluster/update/main.go
service/ocean/spark/cluster.go

[BGD-6259](https://spotinst.atlassian.net/browse/BGD-6259)
Added a new object to the config with an optional property for setting a storage class override for workspaces.
[BGD-6259]: https://spotinst.atlassian.net/browse/BGD-6259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat (ocean/spark): Added 'WorkspacesConfig' to 'Config'  [BGD-6259]

---

service/ocean/providers/aws/clusternodes.go

Changed type of workloadRequestedMemoryInMiB from *int to *float64
**Error**: 
`json: cannot unmarshal number 117224.4 into Go struct field ClusterNodes.workloadRequestedMemoryInMiB of type int`
**Function**: 
`ocean.ServiceOp.CloudProviderAWS().ReadClusterNodes(context.Context, *ReadClusterNodeInput) (*ReadClusterNodeOutput, error)`

Fix: ReadClusterNodeOutput.ClusterNodes[].WorkloadRequestedMemoryInMiB type issue 

---

examples/service/setcredentails/providers/azure/create/main.go
examples/service/setcredentails/providers/azure/read/main.go
service/account/account.go
service/account/providers/azure/azurecredentials.go
service/account/providers/azure/service.go

Supported setCredentials for Azure.
Ref: https://spotinst.atlassian.net/browse/SI-226

Supported setCredentials for Azure.

---

service/elastigroup/providers/aws/aws.go

Added `MaxReplacementsPercentage` field in `strategy` object for elastigroup-aws
https://spotinst.atlassian.net/browse/SI-296

Added `MaxReplacementsPercentage` field in `strategy` object for elastigroup-aws

---

service/ocean/providers/gcp/cluster.go
service/ocean/providers/gcp/launchspec.go

Added `ScalingOrientation` field in `Strategy` object for ocean-gcp-k8s and vng
https://spotinst.atlassian.net/browse/SI-268

Added `ScalingOrientation` field in `strategy` object for ocean-gcp-k8s
